# Generated by Django 3.2.7 on 2021-09-30 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GhqApp', '0002_auto_20210930_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
