# Generated by Django 3.2.7 on 2021-09-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhqApp', '0003_alter_options_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattemptanswer',
            name='user_answer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
