# Generated by Django 3.2.7 on 2021-10-01 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GhqApp', '0004_quizattemptanswer_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaken',
            name='date_test_given',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
